apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-api-deploy
  namespace: university
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-api
  template:
    metadata:
      labels:
        app: department-api
    spec:
      containers:
      - name: department-api
        image: jin604/department-service:1.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8088
